version: '3'

services:
  user_profile_backend:
    build:
      context: ./backend/user_profile_backend
    environment:
      - USER_HOST=http://user_profile_backend:4000/api/users
    ports: 
      - 4000:4000

  history-backend:
    build:
      context: ./backend/question-history-backend
    environment:
      - HISTORY_HOST="http://history-backend:5000/api/history"
      - RABBIT_MQ_HOST=amqp://rabbitmq:5672
    ports:
      - 5000:5000
    depends_on:
      - rabbitmq
    restart: always

  question-backend:
    build:
      context: ./backend/question-backend
    environment:
      - USER_HOST=http://user_profile_backend:4000/api/users
      - QUESTION_HOST=http://question-backend:8000/api/questions
    ports: 
      - 8000:8000
    depends_on:
      - user_profile_backend

  matching_backend:
    build:
      context: ./backend/matching_backend
    ports:
      - 3001:3001
    restart: unless-stopped
    environment:
      - RABBIT_MQ_HOST=amqp://rabbitmq:5672
      - FRONTEND_HOST=http://localhost:3000
      - USER_HOST=http://user_profile_backend:4000/api/users
      - COLLAB_HOST=http://collab-backend:9000
    depends_on:
      - rabbitmq
      - frontend
      - user_profile_backend

  frontend:
    build:
      context: ./frontend
    ports: 
      - 3000:3000
    environment: 
      - REACT_APP_USER_HOST=http://localhost:4000/api/users
      - REACT_APP_QUESTION_HOST=http://localhost:8000/api/questions
      - REACT_APP_MATCHING_HOST=ws://localhost:3001
      - REACT_APP_CATEGORY_HOST=http://localhost:8000/api/categories
      - REACT_APP_COLLAB_HOST=http://localhost:9000
      - REACT_APP_HISTORY_HOST="http://localhost:5000/api/history"
    depends_on:
      - user_profile_backend
      - question-backend

  communication-backend:
    build:
      context: ./backend/communication-backend
    ports:
      - 9001:9001
    environment:
      - FRONTEND_HOST=http://localhost:3000
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  collab-backend:
    build:
      context: ./backend/collab-backend
    ports:
      - 9000:9000
    environment:
      - RABBIT_MQ_HOST=amqp://rabbitmq:5672
      - FRONTEND_HOST=http://localhost:3000
      - MONGODB_URI=mongodb://mongodb_container/document_db
      - QUESTION_HOST=http://question-backend:8000/api/questions

    depends_on:
      - mongodb_container
      - rabbitmq

  mongodb_container:
    image: mongo:latest
    build:
      context: ./backend/collab-backend/mongo
    ports:
      - 27017:27017
